React function components
OSAdams/m3-0822-code-solutions pull request #11
Opened 2022-08-31 04:17 UTC by OSAdams

![image](https://user-images.githubusercontent.com/76730244/187591750-f38b3847-bb72-41bf-b53c-4ab292f3840a.png)

2022-08-31 04:23 UTC, scbowler requested changes
Looking good, but you should be using a `function` component, not a `class` component. Let me know if you have any questions.

2022-08-31 04:23 UTC, scbowler commented on react-function-components/src/index.jsx
> +}
This should be a `function` component

2022-08-31 04:35 UTC, OSAdams commented
![image](https://user-images.githubusercontent.com/76730244/187593621-c035aa45-788f-408b-9b70-43ab3b6c2780.png)

2022-09-01 22:57 UTC, scbowler approved these changes
Looks good! 👍

2022-09-02 00:42 UTC, merged